---
- name: Configure NTP servers on Nokia SR Linux devices
  hosts: sites_denver
  gather_facts: false
  tasks:
    - name: Check and retrieve NTP servers from site custom fields
      set_fact:
        ntp_servers: "{{ hostvars[inventory_hostname].sites[0].custom_fields.ntp_servers.split(',') | map('trim') | list }}"
      when:
        - hostvars[inventory_hostname].sites is defined
        - hostvars[inventory_hostname].sites[0].custom_fields.ntp_servers is defined
        - hostvars[inventory_hostname].sites[0].custom_fields.ntp_servers | trim != ''

    - name: Debug message when no NTP servers are defined
      debug:
        msg: "No NTP servers defined for the site of {{ inventory_hostname }}. Skipping..."
      when: ntp_servers is not defined

    - name: Construct the NTP configuration data
      set_fact:
        ntp_config:
          network-instance: default
          admin-state: enable
          server: "{{ ntp_servers | map('trim') | list | map('regex_replace', '^(.*)$', '{\"address\":\"\\1\"}') | map('from_json') | list }}"
      when: ntp_servers is defined

    - name: Debug message when no NTP servers are defined
      debug:
        msg: "ntp_config: {{ ntp_config }}"

    - name: Enable NTP and configure servers
      nokia.srlinux.config:
        update:
          - path: /system/ntp
            value: "{{ ntp_config }}"
      when: ntp_servers is defined