---
- name: Retrieve hostname from Nokia SR OS router
  hosts: all
  gather_facts: no
  tasks:
    - name: Get /system/information container
      nokia.srlinux.get:
        paths:
          - path: /system/information
            datastore: state
            yang_models: srl
      register: response

    - debug:
        var: response
