---
- name: Query devices from NetBox and Display Output
  hosts: localhost
  gather_facts: no

  vars:
    netbox_url: "{{ lookup('ansible.builtin.env', 'NETBOX_API') }}"
    netbox_token: "{{ lookup('ansible.builtin.env', 'NETBOX_TOKEN') }}"

  tasks:

  - name: Get device data from Netbox
    set_fact:
      device_data: "{{ query('netbox.netbox.nb_lookup', 'devices', api_endpoint=netbox_url, token=netbox_token ) }}"

  - name: Print device name and serial number
    debug:
      msg: "{{ item.value.name }} has serial number {{ item.value.serial }}"
    loop: "{{ device_data }}"
