version: '3.8'

services:
  netbox-napalm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - NETBOX_URL=https://mark.cloud.netboxapp.com/
      - NETBOX_TOKEN=***REMOVED***
      - NAPALM_USERNAME=admin
      - NAPALM_PASSWORD=NokiaSrl1!
    networks:
      - autocon_workshop  # Ensure it's the correct network name
    command: ["fiber", "plane"]

networks:
  autocon_workshop:
    external: true