version: '3.8'

services:
  netbox-napalm:
    build: .
    environment:
      - NETBOX_URL=https://mark.cloud.netboxapp.com/
      - NETBOX_TOKEN=***REMOVED***
      - NAPALM_USERNAME=admin
      - NAPALM_PASSWORD=admin
    command: ["fiber", "plane"]
    volumes:
      - ./configs:/configs