version: '3.8'

services:
  netbox-napalm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - NETBOX_URL=https://yournetbox.com/
      - NETBOX_TOKEN=<NETBOX TOKEN>
      - NAPALM_USERNAME=admin               # Nokia SR Linux Default
      - NAPALM_PASSWORD=NokiaSrl1!          # Nokia SR Linux Default
    networks:
      - autocon_workshop
    command: ["fiber", "plane"]

networks:
  autocon_workshop:
    external: true