x-tag-params: &tag-params
  TAG_CONN_PARAMS: '{"slow":{"timeout":120,"conn_timeout":50,"read_timeout_override":80,"fast_cli":false,"keepalive":5}}'

x-api: &api_common
  image: netpicker/api@sha256:0a1f2be3c975d7b2cf30a008c5f760dc52fcbbfc4bea0794311f2e21f8203099
  environment:
    #API_URL: http://api:8000
    ALLOWED_ORIGINS: '["*"]'
    AUTH0_AUDIENCE: n/a
    AUTH0_CLIENT_ID: n/a
    AUTH0_CLIENT_SECRET: n/a
    AUTH0_TENANT: n/a
    CELERY_BROKER_URL: redis://redis
    CELERY_RESULT_BACKEND: redis://redis
    JWT_AUDIENCE: "netpicker"
    JWT_ALGORITHM: HS256
    JWT_SECRET: ew9023cnkljfcnsdlkfsfdhs
    DB_URI: "postgresql+asyncpg://netpicker:netpicker@db/netpicker"
    BEAT_DB_URI: "postgresql+psycopg2://netpicker:netpicker@db/netpicker"
    PERSISTENT_VOLUME_PATH: /data/policy-repository
    REDIS_URL: redis://redis
    UVICORN_ROOT_PATH: /
    WORKDIR_VOLUME_PATH: /data/policy-workdir
    AUTH_BACKEND: netyce_alchemy
    GIT_SERVER: git://gitd
    GIT_REPO_MANAGER: '["gitd",9419]'
    CLI_PROXY_HOST: agent
    INIT_USER: 'admin@admin.com'
    INIT_PASSWORD: '12345678'
    INIT_TENANT: 'default'
    NETBOX_API: "https://netbox-endpoint/"
    NETBOX_TOKEN: netbox_token_here
    SLURPIT_URL: "https://slurpit-endpoint/"
    SLURPIT_APIKEY: slurpit_apikey_here
    #PUBLIC_POLICIES:
    #PROXY_SSL_VERIFY: 0 # does not verify any SSL certificate
    #PROXY_SSL_VERIFY_EXEMPT_HOST: '["my.host", "your.host"]' # does not verify SSL certificates for given hostnames
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - policy-data:/data
  depends_on:
    - redis
    - db

services:
  db:
    image: netpicker/db@sha256:4a57d4c8f5beca2ed908746553febc55e79027c581d6bb737c21c94d4dff7cfd
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: s3rgts0p!
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - autocon-workshop

  api:
    <<: *api_common
    container_name: api
    labels:
      service.netpicker.io: api
    ports:
      - "${NETPICKER_API_PORT}:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${MY_EXTERNAL_IP}:${NETPICKER_API_PORT}/api/v1/status"]
      start_period: 60s
      interval: 5s
    networks:
      - autocon-workshop

  celery:
    <<: *api_common
    container_name: celery
    labels:
      service.netpicker.io: celery
    command: /run-celery
    healthcheck:
      test: ["CMD", "celery", "inspect", "ping", "-t", "5"]
      start_period: 5s
      interval: 30s
    networks:
      - autocon-workshop

  redis:
    image: redis:7-alpine
    container_name: redis
    #ports:
    #  - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    networks:
      - autocon-workshop

  gitd:
    image: netpicker/gitd@sha256:039cfa42cedc41a1f1bd4143bd010ac8a940a5fbdbcab8c560e346dfc7000c21
    container_name: gitd
    ports:
      - "9418:9418" # Default port for git:// pull/push
      - "9419:9419" # To manage new repos
    volumes:
      - git:/git
    healthcheck:
      test: echo "PING" | nc -v localhost 9419
      start_period: 15s
      interval: 5s
    networks:
      - autocon-workshop

  swagger:
    image: swaggerapi/swagger-ui:v5.17.14
    container_name: swagger
    environment:
      SWAGGER_JSON_URL: "/openapi.json"
      TRY_IT_OUT_ENABLED: true
    ports:
      - "8080:8080"
    depends_on:
      - api
    networks:
      - autocon-workshop

  frontend:
    image: netpicker/frontend@sha256:93b8f3d5182a2bbd6ece7bac0c08d6a5471c7658271513f87784661139ff75e8
    container_name: frontend
    labels:
      service.netpicker.io: front-end
    ports:
      - "${NETPICKER_PORT}:80"
    depends_on:
      - api
    networks:
      - autocon-workshop

  kibbitzer:
    image: netpicker/kibbitzer@sha256:469891a9e36d58f9dd4553de7b583b3d199721d23a68acc9930e6139875784e4
    container_name: kibbitzer
    labels:
      service.netpicker.io: kibbitzer
    environment:
      <<: *tag-params
      SHENV_API_URL: http://api:8000
      #SHENV_CELERY_BROKER_URL: redis://redis
      #SHENV_CELERY_RESULT_BACKEND: redis://redis
      SHENV_SHOW_RUN_nokia_srl: 'info'
      SHENV_SHOW_RUN_mikrotik_routeros: 'export'
      SHENV_TAG_SHOW_RUN_mikrotik_routeros_v7: 'export show-sensitive'
      SHENV_PRIVILEGED_PLATFORMS: 'privileged_platform'
      LOG_LEVEL: DEBUG
    healthcheck:
      test: echo "PING Mac" | nc -v 127.0.0.1 9696
      start_period: 15s
      interval: 30s
    volumes:
      - secret:/run/secrets
    depends_on:
      - redis
    networks:
      - autocon-workshop

  agent:
    hostname: agent
    image: netpicker/agent@sha256:4ead631d6d9e99a229f6209c0ab7ac5d0c23c873b3e976c60bed278d685f4876
    container_name: agent
    labels:
      service.netpicker.io: agent
    environment:
      <<: *tag-params
      CLI_PROXY_ADDR: '0.0.0.0'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - config:/agent-config
      - secret:/run/secrets
      - transferium:/transferium
    ports:
      - 5514:5514/udp
      - 6601:6601/tcp
      - 6514:6514/tcp
      - 8765:8765/tcp
      - 9876:9876/tcp
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: "echo LST | nc -v localhost 8765"
      start_period: 2s
      interval: 5s
    networks:
      - autocon-workshop

volumes:
  policy-data:
  pg_data:
  git:
  config:
  secret:
  transferium:

networks:
  autocon-workshop:
    external: true
