# It's better to overwrite compose changes in this file so that the original will be overwriten when you pull the updates from the git project
# To use the override file, remove -EXAMPLE from the filename and it becomes automatically active when you run up.sh or up.bat
services:
  slurpit-warehouse:
    environment:
      TZ: Europe/Amsterdam
      WAREHOUSE_CALLBACK_SCANNER_URL: http://slurpit-portal/callback/scanner
      WAREHOUSE_CALLBACK_SCANNER_TOKEN: 
      WAREHOUSE_CALLBACK_SCRAPER_URL: http://slurpit-portal/callback/scraper
      WAREHOUSE_CALLBACK_SCRAPER_TOKEN: 

  slurpit-scraper:
    environment:
      TZ: Europe/Amsterdam
      SCRAPER_TIMEOUT: 20
      SCRAPER_POOLSIZE: 8
      SCRAPER_WAREHOUSE_URL: http://slurpit-warehouse

  slurpit-scanner:
    environment:
      TZ: Europe/Amsterdam
      SCANNER_POOLSIZE: 8
      SCANNER_TIMEOUT: 10
      SCANNER_WAREHOUSE_URL: http://slurpit-warehouse

  slurpit-portal:
    environment:
      TZ: Europe/Amsterdam
      PORTAL_BASE_URL: "http://${MY_EXTERNAL_IP}:${SLURPIT_PORT}/"
      PORTAL_WAREHOUSE_URL: http://slurpit-warehouse
    ports: 
      - "${SLURPIT_PORT}:80"