---
plugin: netbox.netbox.nb_inventory
api_endpoint: http://MY_EXTERNAL_IP:NETBOX_PORT
token: 1234567890

max_uri_length: 1000
fetch_all: true
config_context: true
flatten_config_context: true
racks: false
services: false
query_filters:
  - status: 'active'
device_query_filters:
  - has_primary_ip: 'true'

group_by:
  - device_roles
  - sites
  - tags

cache: true
site_data: true
interfaces: true