---
- name: Query devices from NetBox and Generate Export Template
  hosts: localhost
  gather_facts: no

  vars:
    netbox_url: "{{ lookup('ansible.builtin.env', 'NETBOX_API') }}"
    netbox_token: "{{ lookup('ansible.builtin.env', 'NETBOX_TOKEN') }}"

  tasks:

  - name: Get device data from Netbox
    set_fact:
      device_data: "{{ query('netbox.netbox.nb_lookup', 'devices', api_endpoint=netbox_url, token=netbox_token ) }}"

  - name: Generate export template
    set_fact:
      export_template: |
        device name | serial number
        {% for device in device_data %}
         {{ '%-12s' | format(device.value.name) }} {{ '%-10s' | format(device.value.serial) }}
        {% endfor %}

  - name: Print export template to console
    debug:
      var: export_template
